version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/psy_assess_api
      - gems:/app-gems
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  db:
  gems:
