default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: psy_assess_api_development

test:
  <<: *default
  database: psy_assess_api_test

production:
  <<: *default
  database: psy_assess_api_production
  username: psy_assess_api
  password: <%= ENV["PSY_ASSESS_API_DATABASE_PASSWORD"] %>
